spring:
  cache:
    type: caffeine
    cache-names: shortUrlCache
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=600s
  application:
    name: leopard
  profiles:
    active: dev
  task:
    execution:
      pool:
        core-size: 50
        max-size: 500
        queue-capacity: 0
        keep-alive: 60s

leopard:
  code:
    # 生成短链接时，发生重复的时候最多尝试次数，用于保证短码的唯一性
    max-try-times: 10
  task:
    expire-url-clean: 0 0 0 * * ?
  file:
    upload-model: Local
    public-path: /fs
    local-path: /Users/liuxin/Desktop/leopard/upload
security:
  # token 名称（同时也是 cookie 名称）
  token-name: Authorization
  token-prefix: Bearer
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  concurrent: true
  ignore-urls:
    - /api/user/login
    - /{code:^[a-zA-Z0-9]{6}$}
    - /favicon.ico
    - /doc.html
    - /webjars/**
    - /swagger-resources/**
    - /v2/api-docs/**
    - /v3/api-docs/**
    - /swagger-ui/**
    - ${leopard.file.public-path}/**
knife4j:
  production: false
  basic:
    enable: true
    username: admin
    password: 123456
