spring:
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl # 模板文件后缀
    cache: true # 模版缓存
  cache:
    type: caffeine
    cache-names: shortUrlCache
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=600s
  application:
    name: joty
  profiles:
    active: dev
  task:
    execution:
      pool:
        core-size: 50
        max-size: 500
        queue-capacity: 0
        keep-alive: 60s

security:
  # Token名称
  token-name: Authorization
  token-prefix: Bearer
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  concurrent: true
  ignore-urls:
    - /api/user/login
    - /api/v1/**
    - /{code:^[a-zA-Z0-9]{6}$}
    - /favicon.ico
    - /doc.html
    - /webjars/**
    - /swagger-resources/**
    - /v2/api-docs/**
    - /v3/api-docs/**
    - /swagger-ui/**
    - ${joty.file.public-path}/**
server:
  tomcat:
    max-connections: 8192
  port: 8090


